version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: PR title check
    validate:
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex:
            - 'ENG1AIOINT-\d+'
            - 'DRQS-\d+'
    pass:
      - do: comment
        payload:
          body: >
            <h4>:+1: Successfully checked for PR title!</h4>
      - do: labels
        add: 'ready-for-review'
    fail:
      - do: comment
        payload:
          body: >
            <h4>:warning: Please add a JIRA or DRQS issue to the title. If there is no issue, please specify [no-ticket]</h4>
