version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
    pass:
      - do: comment
        payload:
          body: >
            <h2>Successfully checked for PR title</h2>
            :+1:
      - do: labels
        add: 'ready-for-review'
    fail:
      - do: comment
        payload:
          body: >
            :warning:
            <h2>Please add a JIRA or DRQS issue to the title. If there is no issue, please specify [no-ticket]</h2>
