version: 2
mergeable:
  - when: pull_request_review.*
    name: PR title check
    validate:
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex:
            - '[A-Z][A-Z0-9]+-\d+'
            - 'DRQS-\d+'
            - ^\[no-ticket\]
    pass:
      - do: labels
        add: 'ready-for-review'
    fail:
      - do: comment
        payload:
          body: >
            <h4>:warning: Please add a JIRA or DRQS issue to the title. If there is no issue, please specify [no-ticket]</h4>
