version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: PR title check
    validate:
      - do: title
        or:
          - must_include:
              regex: 'ENG1AIOINT-\d+'
          - must_include:
              regex: 'DRQS-\d+'
          - must_include:
              regex: '[no-ticket]'
    pass:
      - do: comment
        payload:
          body: >
            <h4>Successfully checked for PR title</h4>
            :+1:
      - do: labels
        add: 'ready-for-review'
    fail:
      - do: comment
        payload:
          body: >
            :warning:
            <h4>Please add a JIRA or DRQS issue to the title. If there is no issue, please specify [no-ticket]</h4>
